networks:
  mynetwork:
    name: prof-tg-network


services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt:/var/www/letsencrypt

    networks:
      - mynetwork

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_renewal
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt:/var/www/letsencrypt
    entrypoint: /bin/sh
    command: -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/letsencrypt --quiet; sleep 12h & wait $${!}; done;'

volumes:
  nginx_data:
