networks:
  mynetwork:

services:
  bot_massage:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - massage.env
    depends_on:
      - redis_massage
      - db_massage
    networks:
      - mynetwork

  web_massage:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: sh -c "pytest tests/test_backend.py && uvicorn Backend:app --host 0.0.0.0 --port 8001 --reload --proxy-headers"
    ports:
      - "8001:8001"
    env_file:
      - massage.env
    depends_on:
      - redis_massage
      - db_massage
    volumes:
      - pg_data_massage:/var/lib/postgresql/data
    networks:
      - mynetwork


  redis_massage:
    image: "redis:latest"
    ports:
      - "6481:6379"
    networks:
      - mynetwork

  db_massage:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: rynokmassage
      POSTGRES_PASSWORD: 23jQ29155skR9659
      POSTGRES_DB: rynokmassage
    ports:
      - "5434:5432"
    volumes:
      - pg_data_massage:/var/lib/postgresql/data
    networks:
      - mynetwork
  grafana_massage:
    image: grafana/grafana:latest
    container_name: grafana_massage
    ports:
      - "3001:3001"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - mynetwork


volumes:
  pg_data_massage:
  grafana_data:



  