FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
      wget gnupg2 lsb-release \
      build-essential gcc g++ \
      libffi-dev libssl-dev python3-dev python3-wheel pkg-config \
      libpq-dev \
  && wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" \
       > /etc/apt/sources.list.d/pgdg.list \
  && apt-get update && apt-get install -y --no-install-recommends \
      postgresql-client-17 \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Установка рабочей директории
WORKDIR /usr/src/app

# Копируем зависимости и устанавливаем Python-библиотеки
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальной код
COPY . .

# Запуск приложения
CMD ["python", "main.py"]
