version: '3.8'

networks:
  mynetwork:

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "443:443"
    depends_on:
      - redis
      - db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: rynoksmm
      POSTGRES_PASSWORD: 23jQ29155skR9659
      POSTGRES_DB: rynoksmm
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pg_data:
