FROM robd003/python3.10:latest

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt


COPY . .


CMD bash -c "pytest tests/test_backend.py && uvicorn Backend:app --host 0.0.0.0 --port 8000"


