networks:
  mynetwork:

services:
  bot_massage:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - massage.env
    depends_on:
      - redis_massage
      - db_massage
    networks:
      - mynetwork

  web_massage:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: uvicorn Backend:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    env_file:
      - massage.env
    depends_on:
      - redis_massage
      - db_massage
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis_massage:
    image: "redis:latest"
    ports:
      - "6481:6481"
    networks:
      - mynetwork

  db_massage:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: rynokmassage
      POSTGRES_PASSWORD: 23jQ29155skR9659
      POSTGRES_DB: rynokmassage
    ports:
      - "5434:5434"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pg_data:
