
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - redis
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "443:443"
    depends_on:
      - redis
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: rynoksmm
      POSTGRES_PASSWORD: 23jQ29155skR9659
      POSTGRES_DB: rynoksmm
    ports:
      - "5432:5432"
