networks:
  mynetwork:

services:
  bot_smm:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - smm.env
    depends_on:
      - redis_smm
      - db_smm
    networks:
      - mynetwork

  web_smm:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: uvicorn Backend:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - smm.env
    depends_on:
      - redis_smm
      - db_smm
    volumes:
      - pg_data_smm:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis_smm:
    image: "redis:latest"
    ports:
      - "6480:6379"
    networks:
      - mynetwork

  db_smm:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: rynoksmm
      POSTGRES_PASSWORD: 23jQ29155skR9659
      POSTGRES_DB: rynoksmm
    ports:
      - "5433:5433"
    volumes:
      - pg_data_smm:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pg_data_smm:
